-- Orbitamos v3.0 - Supabase native platform schema.
--
-- Este schema convive com as tabelas antigas do backend Spring v2.0.
-- Nao altera nem apaga tabelas legadas como users, user_progress, forum_messages,
-- conversations, conversation_participants e chat_messages.
--
-- Motivo: o legado usa IDs numericos BIGINT; Supabase Auth usa UUID.
-- A v3 usa tabelas prefixadas com v3_* para evitar conflito.

create extension if not exists "pgcrypto";

-- Limpa artefatos de uma tentativa anterior da migration 005 sem prefixo v3.
-- Isso nao apaga dados; apenas impede que um trigger antigo tente inserir UUID
-- nas tabelas legadas BIGINT do Spring.
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();

create table if not exists public.v3_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text not null,
  avatar_url text,
  role text not null default 'STUDENT' check (role in ('STUDENT', 'FREELANCER')),
  phone text,
  birth_date date,
  address text,
  city text,
  neighborhood text,
  state text,
  zip_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.v3_user_progress (
  user_id uuid primary key references public.v3_profiles(id) on delete cascade,
  percent integer not null default 0,
  phase text not null default 'Planeta Terra - Fundacao',
  next_goal text not null default 'Finalizar o Modulo 1 de fundamentos',
  level integer not null default 1,
  xp integer not null default 0,
  streak_days integer not null default 0,
  last_lesson text,
  updated_at timestamptz not null default now()
);

create table if not exists public.v3_contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.v3_forum_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.v3_profiles(id) on delete cascade,
  content text not null,
  city text,
  neighborhood text,
  parent_id bigint references public.v3_forum_messages(id) on delete cascade,
  topic_title text,
  topic_color text,
  topic_emoji text,
  created_at timestamptz not null default now()
);

create table if not exists public.v3_conversations (
  id bigint generated by default as identity primary key,
  type text not null default 'DIRECT' check (type in ('DIRECT', 'GROUP')),
  name text,
  avatar_url text,
  created_by_user_id uuid references public.v3_profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.v3_conversation_participants (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.v3_conversations(id) on delete cascade,
  user_id uuid not null references public.v3_profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  unique (conversation_id, user_id)
);

create table if not exists public.v3_chat_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.v3_conversations(id) on delete cascade,
  sender_id uuid not null references public.v3_profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create or replace function public.v3_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists v3_profiles_touch_updated_at on public.v3_profiles;
create trigger v3_profiles_touch_updated_at
before update on public.v3_profiles
for each row execute function public.v3_touch_updated_at();

drop trigger if exists v3_user_progress_touch_updated_at on public.v3_user_progress;
create trigger v3_user_progress_touch_updated_at
before update on public.v3_user_progress
for each row execute function public.v3_touch_updated_at();

create or replace function public.v3_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.v3_profiles (id, email, name, role)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'name', split_part(coalesce(new.email, ''), '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'role', 'STUDENT')
  )
  on conflict (id) do nothing;

  insert into public.v3_user_progress (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists v3_on_auth_user_created on auth.users;
create trigger v3_on_auth_user_created
after insert on auth.users
for each row execute function public.v3_handle_new_user();

alter table public.v3_profiles enable row level security;
alter table public.v3_user_progress enable row level security;
alter table public.v3_contacts enable row level security;
alter table public.v3_forum_messages enable row level security;
alter table public.v3_conversations enable row level security;
alter table public.v3_conversation_participants enable row level security;
alter table public.v3_chat_messages enable row level security;

drop policy if exists "v3_profiles_select_authenticated" on public.v3_profiles;
create policy "v3_profiles_select_authenticated"
on public.v3_profiles for select
to authenticated
using (true);

drop policy if exists "v3_profiles_insert_own" on public.v3_profiles;
create policy "v3_profiles_insert_own"
on public.v3_profiles for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "v3_profiles_update_own" on public.v3_profiles;
create policy "v3_profiles_update_own"
on public.v3_profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "v3_progress_select_own" on public.v3_user_progress;
create policy "v3_progress_select_own"
on public.v3_user_progress for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "v3_progress_insert_own" on public.v3_user_progress;
create policy "v3_progress_insert_own"
on public.v3_user_progress for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "v3_progress_update_own" on public.v3_user_progress;
create policy "v3_progress_update_own"
on public.v3_user_progress for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "v3_contacts_insert_public" on public.v3_contacts;
create policy "v3_contacts_insert_public"
on public.v3_contacts for insert
to anon, authenticated
with check (true);

drop policy if exists "v3_contacts_select_authenticated" on public.v3_contacts;
create policy "v3_contacts_select_authenticated"
on public.v3_contacts for select
to authenticated
using (true);

drop policy if exists "v3_contacts_update_authenticated" on public.v3_contacts;
create policy "v3_contacts_update_authenticated"
on public.v3_contacts for update
to authenticated
using (true)
with check (true);

drop policy if exists "v3_forum_select_all" on public.v3_forum_messages;
create policy "v3_forum_select_all"
on public.v3_forum_messages for select
to anon, authenticated
using (true);

drop policy if exists "v3_forum_insert_own" on public.v3_forum_messages;
create policy "v3_forum_insert_own"
on public.v3_forum_messages for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "v3_forum_update_own" on public.v3_forum_messages;
create policy "v3_forum_update_own"
on public.v3_forum_messages for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "v3_forum_delete_own" on public.v3_forum_messages;
create policy "v3_forum_delete_own"
on public.v3_forum_messages for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "v3_conversations_select_participant" on public.v3_conversations;
create policy "v3_conversations_select_participant"
on public.v3_conversations for select
to authenticated
using (
  exists (
    select 1 from public.v3_conversation_participants cp
    where cp.conversation_id = v3_conversations.id and cp.user_id = auth.uid()
  )
);

drop policy if exists "v3_conversations_insert_authenticated" on public.v3_conversations;
create policy "v3_conversations_insert_authenticated"
on public.v3_conversations for insert
to authenticated
with check (auth.uid() = created_by_user_id or created_by_user_id is null);

drop policy if exists "v3_conversations_update_creator" on public.v3_conversations;
create policy "v3_conversations_update_creator"
on public.v3_conversations for update
to authenticated
using (auth.uid() = created_by_user_id)
with check (auth.uid() = created_by_user_id);

drop policy if exists "v3_participants_select_participant" on public.v3_conversation_participants;
create policy "v3_participants_select_participant"
on public.v3_conversation_participants for select
to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1 from public.v3_conversation_participants mine
    where mine.conversation_id = v3_conversation_participants.conversation_id and mine.user_id = auth.uid()
  )
);

drop policy if exists "v3_participants_insert_authenticated" on public.v3_conversation_participants;
create policy "v3_participants_insert_authenticated"
on public.v3_conversation_participants for insert
to authenticated
with check (true);

drop policy if exists "v3_participants_delete_self_or_creator" on public.v3_conversation_participants;
create policy "v3_participants_delete_self_or_creator"
on public.v3_conversation_participants for delete
to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1 from public.v3_conversations c
    where c.id = v3_conversation_participants.conversation_id and c.created_by_user_id = auth.uid()
  )
);

drop policy if exists "v3_messages_select_participant" on public.v3_chat_messages;
create policy "v3_messages_select_participant"
on public.v3_chat_messages for select
to authenticated
using (
  exists (
    select 1 from public.v3_conversation_participants cp
    where cp.conversation_id = v3_chat_messages.conversation_id and cp.user_id = auth.uid()
  )
);

drop policy if exists "v3_messages_insert_participant" on public.v3_chat_messages;
create policy "v3_messages_insert_participant"
on public.v3_chat_messages for insert
to authenticated
with check (
  auth.uid() = sender_id
  and exists (
    select 1 from public.v3_conversation_participants cp
    where cp.conversation_id = v3_chat_messages.conversation_id and cp.user_id = auth.uid()
  )
);

create index if not exists v3_forum_messages_parent_created_idx on public.v3_forum_messages(parent_id, created_at desc);
create index if not exists v3_chat_messages_conversation_created_idx on public.v3_chat_messages(conversation_id, created_at);
create index if not exists v3_conversation_participants_user_idx on public.v3_conversation_participants(user_id);
