-- Orbitamos v3: dados reais da area do colaborador
create table if not exists public.v3_collaborator_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  headline text, bio text,
  availability text not null default 'available' check (availability in ('available','partial','unavailable')),
  skills text[] not null default '{}', portfolio_urls text[] not null default '{}',
  updated_at timestamptz not null default now()
);
create table if not exists public.v3_jobs (
  id bigint generated by default as identity primary key, title text not null,
  description text not null default '', type text not null default 'freela',
  work_model text not null default 'remoto', status text not null default 'draft' check (status in ('draft','open','paused','closed')),
  skills text[] not null default '{}', budget_label text, published_at timestamptz, created_at timestamptz not null default now()
);
create table if not exists public.v3_job_applications (
  id bigint generated by default as identity primary key, job_id bigint not null references public.v3_jobs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade, cover_letter text,
  status text not null default 'pending' check (status in ('pending','reviewing','accepted','declined','withdrawn')),
  feedback text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(job_id,user_id)
);
create table if not exists public.v3_collaborator_projects (
  id bigint generated by default as identity primary key, title text not null, description text not null default '',
  status text not null default 'todo' check (status in ('todo','in_progress','completed','paused')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.v3_project_members (
  project_id bigint not null references public.v3_collaborator_projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade, role_label text, joined_at timestamptz not null default now(), primary key(project_id,user_id)
);
alter table public.v3_collaborator_profiles enable row level security;
alter table public.v3_jobs enable row level security;
alter table public.v3_job_applications enable row level security;
alter table public.v3_collaborator_projects enable row level security;
alter table public.v3_project_members enable row level security;
create policy "profiles readable" on public.v3_collaborator_profiles for select to authenticated using (true);
create policy "own professional profile" on public.v3_collaborator_profiles for all to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "read open jobs" on public.v3_jobs for select to authenticated using (status='open');
create policy "read own applications" on public.v3_job_applications for select to authenticated using (auth.uid()=user_id);
create policy "create own applications" on public.v3_job_applications for insert to authenticated with check (auth.uid()=user_id);
create policy "update own applications" on public.v3_job_applications for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "read member projects" on public.v3_collaborator_projects for select to authenticated using (exists(select 1 from public.v3_project_members m where m.project_id=id and m.user_id=auth.uid()));
create or replace function public.is_v3_project_member(target_project_id bigint)
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.v3_project_members where project_id=target_project_id and user_id=auth.uid()) $$;
revoke all on function public.is_v3_project_member(bigint) from public;
grant execute on function public.is_v3_project_member(bigint) to authenticated;
create policy "read shared memberships" on public.v3_project_members for select to authenticated using (public.is_v3_project_member(project_id));
create index if not exists v3_jobs_status_idx on public.v3_jobs(status,published_at desc);
create index if not exists v3_applications_user_idx on public.v3_job_applications(user_id,created_at desc);
create index if not exists v3_project_members_user_idx on public.v3_project_members(user_id);
