-- Orbitamos v3 - Rate limit do formulario de contato no banco.
-- Executar depois de 014. Nao apaga dados de contatos.
--
-- Antes: o limite (5 envios / 10 min por IP) vivia so na memoria do servidor,
-- que zera a cada cold start e nao e compartilhado entre instancias na Vercel
-- (facil de burlar). Agora o controle fica no Postgres, compartilhado e persistente.
--
-- Guarda apenas um HASH do IP (nao o IP em texto puro), por privacidade.

create table if not exists public.v3_contact_attempts (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists v3_contact_attempts_ip_time_idx
  on public.v3_contact_attempts (ip_hash, created_at desc);

-- Ninguem acessa a tabela direto pelo client; somente a funcao definer abaixo.
alter table public.v3_contact_attempts enable row level security;

-- Retorna true se o envio e permitido (e registra a tentativa), false se estourou o limite.
create or replace function public.v3_contact_rate_check(
  p_ip_hash text,
  p_max int default 5,
  p_window_secs int default 600
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  recent int;
begin
  -- limpeza oportunista de registros antigos (mantem a tabela pequena)
  delete from public.v3_contact_attempts where created_at < now() - interval '1 day';

  select count(*) into recent
  from public.v3_contact_attempts
  where ip_hash = p_ip_hash
    and created_at > now() - make_interval(secs => p_window_secs);

  if recent >= p_max then
    return false;
  end if;

  insert into public.v3_contact_attempts (ip_hash) values (p_ip_hash);
  return true;
end;
$$;

revoke all on function public.v3_contact_rate_check(text, int, int) from public;
grant execute on function public.v3_contact_rate_check(text, int, int) to anon, authenticated, service_role;
