"use client";

import { useEffect, useState } from "react";
import { Check, Globe, Loader2, MapPin, Pencil, Plus, X } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { getCollaboratorProfile, getDisplayAvatarUrl, saveCollaboratorProfile, type CollaboratorProfile } from "@/lib/api";

const empty: CollaboratorProfile = { headline: "", bio: "", availability: "available", skills: [], portfolioUrls: [], preferredJobTypes: [], preferredWorkModels: [], weeklyHours: null, minimumBudget: null, openToContact: true, profileVisible: true };
const availability = { available: "Disponível", partial: "Disponibilidade parcial", unavailable: "Indisponível" };

export default function ColaboradorPerfil() {
  const { user } = useAuth();
  const [profile, setProfile] = useState(empty);
  const [draft, setDraft] = useState(empty);
  const [editing, setEditing] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const [skill, setSkill] = useState("");
  const [url, setUrl] = useState("");
  useEffect(() => { getCollaboratorProfile().then((data) => { setProfile(data); setDraft(data); }).catch((e) => setMessage(e instanceof Error ? e.message : "Erro ao carregar perfil")).finally(() => setLoading(false)); }, []);
  const save = async () => { setSaving(true); setMessage(""); try { const saved = await saveCollaboratorProfile(draft); setProfile(saved); setEditing(false); setMessage("Perfil profissional atualizado."); } catch (e) { setMessage(e instanceof Error ? e.message : "Erro ao salvar"); } finally { setSaving(false); } };
  const initials = user?.name?.split(" ").map(n => n[0]).slice(0,2).join("").toUpperCase() ?? "?";
  const completion = [profile.headline, profile.bio, profile.skills.length, profile.portfolioUrls.length, user?.avatarUrl].filter(Boolean).length * 20;
  if (loading) return <div className="py-24 text-center text-sm text-white/40">Carregando perfil profissional...</div>;

  return <div className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-orbit-purple/70">Presença profissional</p><h1 className="mt-1 text-2xl font-black text-white">Meu perfil</h1><p className="mt-1 text-sm text-white/45">Dados reais usados para apresentar seu trabalho e combinar oportunidades.</p></div>{editing ? <div className="flex gap-2"><button onClick={() => { setDraft(profile); setEditing(false); }} className="min-h-11 rounded-xl border border-white/10 px-4 text-xs text-white/60">Cancelar</button><button onClick={save} disabled={saving} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-orbit-electric px-4 text-xs font-bold text-black disabled:opacity-50">{saving ? <Loader2 className="size-4 animate-spin" /> : <Check className="size-4" />}Salvar</button></div> : <button onClick={() => setEditing(true)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-orbit-purple/30 bg-orbit-purple/10 px-4 text-xs font-bold text-orbit-purple"><Pencil className="size-4" />Editar perfil</button>}</div>
    {message && <div className="rounded-xl border border-white/10 bg-white/5 p-3 text-sm text-white/65">{message}</div>}
    <div className="grid gap-5 lg:grid-cols-[1fr_280px]">
      <section className="space-y-5 rounded-2xl border border-white/10 bg-white/[0.025] p-5 sm:p-7">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center">{getDisplayAvatarUrl(user?.avatarUrl) ? <img src={getDisplayAvatarUrl(user?.avatarUrl)!} alt="" className="size-20 rounded-2xl object-cover" /> : <div className="grid size-20 place-items-center rounded-2xl bg-gradient-to-br from-orbit-electric/30 to-orbit-purple/30 text-xl font-black">{initials}</div>}<div><h2 className="text-xl font-black text-white">{user?.name}</h2>{editing ? <input value={draft.headline} onChange={e => setDraft({...draft, headline:e.target.value})} placeholder="Ex.: Desenvolvedor Front-end" className="mt-2 h-10 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-sm text-white outline-none focus:border-orbit-electric/50" /> : <p className="mt-1 text-sm text-white/50">{profile.headline || "Adicione um título profissional"}</p>}<p className="mt-2 flex items-center gap-1.5 text-xs text-white/35"><MapPin className="size-3" />{[user?.city,user?.state].filter(Boolean).join(" / ") || "Localização não informada"}</p></div></div>
        <div><label className="text-[10px] font-bold uppercase tracking-[.15em] text-white/35">Sobre</label>{editing ? <textarea value={draft.bio} onChange={e => setDraft({...draft,bio:e.target.value})} rows={5} maxLength={700} placeholder="Conte sua experiência, especialidades e o tipo de problema que você resolve." className="mt-2 w-full resize-none rounded-xl border border-white/10 bg-black/20 p-3 text-sm text-white outline-none focus:border-orbit-electric/50" /> : <p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-white/60">{profile.bio || "Sua apresentação profissional aparecerá aqui quando você completar o perfil."}</p>}</div>
        <div><label className="text-[10px] font-bold uppercase tracking-[.15em] text-white/35">Habilidades</label><div className="mt-2 flex flex-wrap gap-2">{draft.skills.map(s => <span key={s} className="inline-flex items-center gap-1 rounded-full border border-orbit-electric/20 bg-orbit-electric/10 px-3 py-1 text-xs text-orbit-electric">{s}{editing && <button onClick={() => setDraft({...draft,skills:draft.skills.filter(x=>x!==s)})}><X className="size-3" /></button>}</span>)}{!draft.skills.length && !editing && <span className="text-sm text-white/35">Nenhuma habilidade adicionada.</span>}</div>{editing && <div className="mt-3 flex gap-2"><input value={skill} onChange={e=>setSkill(e.target.value)} placeholder="Adicionar habilidade" className="h-10 flex-1 rounded-lg border border-white/10 bg-black/20 px-3 text-sm text-white outline-none"/><button onClick={()=>{const v=skill.trim();if(v&&!draft.skills.includes(v))setDraft({...draft,skills:[...draft.skills,v]});setSkill("");}} className="grid size-10 place-items-center rounded-lg bg-white/10"><Plus className="size-4" /></button></div>}</div>
        <div><label className="text-[10px] font-bold uppercase tracking-[.15em] text-white/35">Portfólio e links</label><div className="mt-2 space-y-2">{draft.portfolioUrls.map(link => <div key={link} className="flex items-center gap-2 rounded-lg border border-white/8 bg-black/20 px-3 py-2"><Globe className="size-4 text-orbit-purple"/><a href={link} target="_blank" rel="noreferrer" className="min-w-0 flex-1 truncate text-xs text-orbit-electric">{link}</a>{editing&&<button onClick={()=>setDraft({...draft,portfolioUrls:draft.portfolioUrls.filter(x=>x!==link)})}><X className="size-4 text-white/40"/></button>}</div>)}{!draft.portfolioUrls.length&&!editing&&<p className="text-sm text-white/35">Nenhum link adicionado.</p>}</div>{editing&&<div className="mt-3 flex gap-2"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://seuportfolio.com" className="h-10 flex-1 rounded-lg border border-white/10 bg-black/20 px-3 text-sm text-white outline-none"/><button onClick={()=>{try{const value=new URL(url).toString();if(!draft.portfolioUrls.includes(value))setDraft({...draft,portfolioUrls:[...draft.portfolioUrls,value]});setUrl("");}catch{setMessage("Informe um link válido com https://");}}} className="grid size-10 place-items-center rounded-lg bg-white/10"><Plus className="size-4"/></button></div>}</div>
      </section>
      <aside className="space-y-4"><div className="rounded-2xl border border-white/10 bg-white/[0.025] p-5"><div className="flex items-center justify-between"><span className="text-sm font-bold text-white">Perfil completo</span><span className="text-sm font-black text-orbit-electric">{completion}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-orbit-electric to-orbit-purple" style={{width:`${completion}%`}} /></div><p className="mt-3 text-xs leading-5 text-white/40">Perfis completos ajudam a equipe a encontrar a pessoa certa para cada projeto.</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.025] p-5"><p className="text-xs font-bold uppercase tracking-wider text-white/35">Disponibilidade</p>{editing ? <select value={draft.availability} onChange={e=>setDraft({...draft,availability:e.target.value as CollaboratorProfile["availability"]})} className="mt-3 h-11 w-full rounded-lg border border-white/10 bg-[#111827] px-3 text-sm text-white"><option value="available">Disponível</option><option value="partial">Parcial</option><option value="unavailable">Indisponível</option></select> : <p className="mt-3 text-sm font-semibold text-emerald-300">{availability[profile.availability]}</p>}</div></aside>
    </div>
  </div>;
}
