"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import WorkspaceWelcome from "@/components/brand/WorkspaceWelcome";
import { MessageCircle } from "lucide-react";
import { getDisplayAvatarUrl, getSquadMembers } from "@/lib/api";
type Member = Awaited<ReturnType<typeof getSquadMembers>>[number];
export default function ColaboradorSquad() {
  const [members,setMembers]=useState<Member[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  useEffect(()=>{getSquadMembers().then(setMembers).catch(e=>setError(e instanceof Error?e.message:"Erro ao carregar equipe")).finally(()=>setLoading(false));},[]);
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-orbit-purple/70">Projetos compartilhados</p><h1 className="mt-1 text-2xl font-black text-white">Meu squad</h1><p className="mt-1 text-sm text-white/45">Pessoas que trabalham com você nos projetos atuais.</p></div>{error&&<div className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">{error}</div>}{loading?<div className="py-20 text-center text-sm text-white/40">Carregando squad...</div>:members.length===0?<WorkspaceWelcome kind="squad"/>:<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{members.map(m=><article key={m.id} className="rounded-2xl border border-white/10 bg-white/[0.025] p-5"><div className="flex items-center gap-3">{getDisplayAvatarUrl(m.avatarUrl)?<img src={getDisplayAvatarUrl(m.avatarUrl)!} alt="" className="size-12 rounded-xl object-cover"/>:<div className="grid size-12 place-items-center rounded-xl bg-gradient-to-br from-orbit-electric/25 to-orbit-purple/25 text-sm font-black">{m.name.split(" ").map(n=>n[0]).slice(0,2).join("")}</div>}<div className="min-w-0"><h2 className="truncate text-sm font-bold text-white">{m.name}</h2><p className="truncate text-xs text-white/40">{m.headline}</p></div></div><div className="mt-4 flex flex-wrap gap-1.5">{m.skills.length?m.skills.slice(0,6).map(s=><span key={s} className="rounded-full bg-white/5 px-2 py-1 text-[10px] text-white/50">{s}</span>):<span className="text-xs text-white/30">Habilidades não informadas</span>}</div></article>)}</div>}<Link href="/mensagens" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-gradient-to-r from-orbit-electric to-orbit-purple px-5 text-xs font-bold text-black"><MessageCircle className="size-4"/>Conversar com a equipe</Link></div>;
}
