-- Orbitamos v3: seguranca operacional, administracao e colaboracao.
-- Executar depois de 010 e 011.

alter table public.v3_profiles
  add column if not exists admin_role text not null default 'none'
  check (admin_role in ('none','staff','admin'));

revoke update (admin_role) on public.v3_profiles from anon, authenticated;

create or replace function public.v3_is_staff()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.v3_profiles where id=auth.uid() and admin_role in ('staff','admin')) $$;
create or replace function public.v3_is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.v3_profiles where id=auth.uid() and admin_role='admin') $$;
revoke all on function public.v3_is_staff() from public;
revoke all on function public.v3_is_admin() from public;
grant execute on function public.v3_is_staff() to authenticated;
grant execute on function public.v3_is_admin() to authenticated;

alter table public.v3_jobs
  add column if not exists requirements text[] not null default '{}',
  add column if not exists scope text,
  add column if not exists openings integer not null default 1 check (openings between 1 and 100),
  add column if not exists application_deadline date,
  add column if not exists created_by uuid references auth.users(id) on delete set null;

alter table public.v3_collaborator_projects
  add column if not exists client_name text,
  add column if not exists priority text not null default 'medium' check (priority in ('low','medium','high','urgent')),
  add column if not exists start_date date,
  add column if not exists due_date date,
  add column if not exists progress integer not null default 0 check (progress between 0 and 100),
  add column if not exists briefing text,
  add column if not exists links jsonb not null default '[]'::jsonb,
  add column if not exists owner_user_id uuid references auth.users(id) on delete set null;

create table if not exists public.v3_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null default 'system',
  title text not null,
  body text not null default '',
  href text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.v3_portfolio_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text not null default '',
  project_url text,
  image_url text,
  skills text[] not null default '{}',
  featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.v3_account_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null default 'deletion' check (type in ('deletion','data_export')),
  status text not null default 'pending' check (status in ('pending','processing','completed','cancelled')),
  reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.v3_notifications enable row level security;
alter table public.v3_portfolio_items enable row level security;
alter table public.v3_account_requests enable row level security;

-- Candidato nao pode mais aceitar/recusar a propria candidatura.
drop policy if exists "update own applications" on public.v3_job_applications;
revoke update on public.v3_job_applications from authenticated;
grant update on public.v3_job_applications to authenticated;

create or replace function public.v3_withdraw_application(application_id bigint)
returns void language plpgsql security definer set search_path=public
as $$
begin
  update public.v3_job_applications
  set status='withdrawn', updated_at=now()
  where id=application_id and user_id=auth.uid() and status in ('pending','reviewing');
  if not found then raise exception 'Candidatura nao encontrada ou nao pode ser retirada'; end if;
end;
$$;
revoke all on function public.v3_withdraw_application(bigint) from public;
grant execute on function public.v3_withdraw_application(bigint) to authenticated;

-- Operacao administrativa.
create policy "staff manage jobs" on public.v3_jobs for all to authenticated using (public.v3_is_staff()) with check (public.v3_is_staff());
create policy "staff read applications" on public.v3_job_applications for select to authenticated using (public.v3_is_staff());
create policy "staff update applications" on public.v3_job_applications for update to authenticated using (public.v3_is_staff()) with check (public.v3_is_staff());
create policy "staff manage projects" on public.v3_collaborator_projects for all to authenticated using (public.v3_is_staff()) with check (public.v3_is_staff());
create policy "staff manage project members" on public.v3_project_members for all to authenticated using (public.v3_is_staff()) with check (public.v3_is_staff());

create policy "users read own notifications" on public.v3_notifications for select to authenticated using (auth.uid()=user_id);
create policy "users update own notifications" on public.v3_notifications for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "staff create notifications" on public.v3_notifications for insert to authenticated with check (public.v3_is_staff());

create policy "users manage own portfolio" on public.v3_portfolio_items for all to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "visible portfolio is readable" on public.v3_portfolio_items for select to authenticated using (
  auth.uid()=user_id or exists(select 1 from public.v3_collaborator_profiles cp where cp.user_id=v3_portfolio_items.user_id and cp.profile_visible=true)
);
create policy "users create account requests" on public.v3_account_requests for insert to authenticated with check (auth.uid()=user_id);
create policy "users read own account requests" on public.v3_account_requests for select to authenticated using (auth.uid()=user_id);
create policy "staff manage account requests" on public.v3_account_requests for all to authenticated using (public.v3_is_admin()) with check (public.v3_is_admin());

-- Notifica automaticamente mudancas importantes.
create or replace function public.v3_notify_application_status()
returns trigger language plpgsql security definer set search_path=public
as $$
declare job_title text;
begin
  if old.status is distinct from new.status then
    select title into job_title from public.v3_jobs where id=new.job_id;
    insert into public.v3_notifications(user_id,type,title,body,href)
    values(new.user_id,'application','Candidatura atualizada',coalesce(job_title,'Oportunidade') || ': ' || case new.status when 'reviewing' then 'em analise' when 'accepted' then 'aceita' when 'declined' then 'processo encerrado' else new.status end,'/colaborador/candidaturas');
  end if;
  return new;
end;
$$;
drop trigger if exists v3_application_status_notification on public.v3_job_applications;
create trigger v3_application_status_notification after update of status on public.v3_job_applications for each row execute function public.v3_notify_application_status();

create or replace function public.v3_notify_project_member()
returns trigger language plpgsql security definer set search_path=public
as $$
declare project_title text;
begin
  select title into project_title from public.v3_collaborator_projects where id=new.project_id;
  insert into public.v3_notifications(user_id,type,title,body,href)
  values(new.user_id,'project','Voce entrou em um projeto',coalesce(project_title,'Novo projeto'),'/colaborador/projetos');
  return new;
end;
$$;
drop trigger if exists v3_project_member_notification on public.v3_project_members;
create trigger v3_project_member_notification after insert on public.v3_project_members for each row execute function public.v3_notify_project_member();

create index if not exists v3_notifications_user_unread_idx on public.v3_notifications(user_id,read_at,created_at desc);
create index if not exists v3_portfolio_user_order_idx on public.v3_portfolio_items(user_id,sort_order,created_at desc);
create unique index if not exists v3_account_requests_one_pending_idx on public.v3_account_requests(user_id,type) where status in ('pending','processing');

-- Depois de executar, promova somente sua conta principal:
-- update public.v3_profiles set admin_role='admin', is_internal=true where email='SEU_EMAIL';
