import { csharpPilot, csharpProgressKey, readCSharpProgress } from "./csharpTrack";

type ActivityBase = { id: string; title: string; topic: string; goal: string };
export type VariableCode = ActivityBase & { kind: "code"; lesson: string; brief: string; hint: string; starter: string; expected: string; verification: string; required: RegExp[]; solution: string; cases?: { label: string; values: Record<string, string>; expected: string }[] };
export type VariableQuiz = ActivityBase & { kind: "quiz"; prompt: string; code?: string; options: string[]; answer: number; feedback: string[] };
export type VariableActivity = VariableCode | VariableQuiz | (ActivityBase & { kind: "guided" });

export const variableActivities: VariableActivity[] = [
  { id: "guided", kind: "guided", title: "Guarde seus primeiros valores", topic: "string, int e console", goal: "Declarar um texto e um número e mostrar os valores no console." },
  { id: "quiz-values", kind: "quiz", title: "Nome ou valor?", topic: "Variável × texto literal", goal: "Distinguir o nome da variável do valor guardado nela.", prompt: "Qual é a saída, na ordem?", code: 'string cliente = "Lia";\nConsole.WriteLine(cliente);\nConsole.WriteLine("cliente");', options: ["cliente, depois cliente", "Lia, depois cliente", "Lia, depois Lia"], answer: 1, feedback: ["Na primeira chamada não há aspas: o programa busca o valor guardado, Lia.", "Isso! Sem aspas, cliente acessa o valor Lia. Entre aspas, é o texto literal cliente.", "A segunda chamada usa aspas: ela imprime o texto cliente, sem consultar a variável."] },
  { id: "client", kind: "code", title: "Cadastre o nome do cliente", topic: "Variáveis de texto", goal: "Escrever uma variável string sem copiar um programa pronto.", lesson: 'string guarda texto. Escreva o tipo, um nome, o sinal = e o texto entre aspas. Termine com ;. Console.WriteLine recebe o nome da variável para mostrar seu valor.', brief: 'Crie uma string chamada cliente com o valor "Lia". Mostre cliente no console. Comece do zero.', hint: 'A declaração começa com string cliente =. Coloque Lia entre aspas. Na chamada Console.WriteLine, use cliente sem aspas.', starter: "", expected: "Lia", verification: 'Console.WriteLine(cliente == "Lia");', required: [/\bstring\s+cliente\s*=/, /Console\.WriteLine\s*\(\s*cliente\s*\)/], solution: 'string cliente = "Lia";\nConsole.WriteLine(cliente);' },
  { id: "transfer", kind: "code", title: "Conte os serviços pendentes", topic: "Números inteiros", goal: "Escolher int para representar uma quantidade inteira.", lesson: "int representa um número inteiro. Ao guardar uma quantidade, não coloque o número entre aspas: 5 é um número; \"5\" é texto.", brief: "Crie uma variável inteira chamada servicosPendentes com valor 5 e mostre essa variável no console. Escreva seu próprio programa.", hint: "Use int antes de servicosPendentes. Console.WriteLine recebe o nome da variável, não o número fixo 5.", starter: "", expected: "5", verification: "Console.WriteLine(servicosPendentes == 5);", required: [/\bint\s+servicosPendentes\s*=/, /Console\.WriteLine\s*\(\s*servicosPendentes\s*\)/], solution: "int servicosPendentes = 5;\nConsole.WriteLine(servicosPendentes);" },
  { id: "quiz-types", kind: "quiz", title: "Qual tipo faz sentido?", topic: "Escolha de tipos", goal: "Relacionar texto e quantidade aos tipos string e int.", prompt: "Para guardar o nome de um cliente e a quantidade inteira de serviços, qual par faz sentido?", options: ["int para o nome; string para a quantidade", "string para os dois, sempre", "string para o nome; int para a quantidade"], answer: 2, feedback: ["O nome é texto, então precisa de string. A quantidade inteira pode usar int.", "Guardar a quantidade como texto dificultaria fazer contas. Use int quando quiser representar uma contagem.", "Certo. O tipo expressa o dado: nome é texto e quantidade é um número inteiro."] },
  { id: "update", kind: "code", title: "Atualize a quantidade", topic: "Reatribuição", goal: "Mudar o valor de uma variável sem declará-la de novo.", lesson: "Depois de declarar uma variável, use seu nome e = para trocar o valor. Não repita int. Você pode usar o valor anterior numa conta: quantidade = quantidade + 2. O atalho quantidade += 2 faz a mesma soma.", brief: "Comece com servicosPendentes igual a 3. Chegaram mais dois serviços: atualize a mesma variável somando 2 ao valor anterior. Mostre o resultado. Não troque apenas o 3 inicial por 5.", hint: "Declare int servicosPendentes = 3; na primeira linha. Depois use servicosPendentes = servicosPendentes + 2; ou servicosPendentes += 2;. Por fim, mostre a variável.", starter: "", expected: "5", verification: "Console.WriteLine(servicosPendentes == 5);", required: [/\bint\s+servicosPendentes\s*=\s*3\s*;/, /\bservicosPendentes\s*(?:\+=\s*2|=\s*servicosPendentes\s*\+\s*2)\s*;/, /Console\.WriteLine\s*\(\s*servicosPendentes\s*\)/], solution: "int servicosPendentes = 3;\nservicosPendentes = servicosPendentes + 2;\nConsole.WriteLine(servicosPendentes);" },
  { id: "remaining", kind: "code", title: "Calcule o que falta entregar", topic: "Expressões com variáveis", goal: "Derivar um valor usando outras variáveis, sem fixar a resposta.", lesson: "Uma variável também pode guardar o resultado de uma conta. Por exemplo: int saldo = entradas - saidas;. Os nomes na expressão fornecem os valores usados na subtração.", brief: "Declare totalServicos com 8 e servicosConcluidos com 3, ambos int. Crie int servicosPendentes calculando totalServicos - servicosConcluidos. Mostre servicosPendentes.", hint: "São três declarações e uma saída. A terceira declaração usa os nomes das duas primeiras variáveis, separados por -.", starter: "", expected: "5", verification: "Console.WriteLine(totalServicos == 8);\nConsole.WriteLine(servicosConcluidos == 3);\nConsole.WriteLine(servicosPendentes == 5);", required: [/\bint\s+totalServicos\s*=/, /\bint\s+servicosConcluidos\s*=/, /\bint\s+servicosPendentes\s*=\s*totalServicos\s*-\s*servicosConcluidos\s*;/, /Console\.WriteLine\s*\(\s*servicosPendentes\s*\)/], solution: "int totalServicos = 8;\nint servicosConcluidos = 3;\nint servicosPendentes = totalServicos - servicosConcluidos;\nConsole.WriteLine(servicosPendentes);" },
  { id: "debug", kind: "code", title: "Encontre o nome errado", topic: "Leitura de erros", goal: "Identificar que maiúsculas e minúsculas fazem parte do nome.", lesson: "Em C#, servicosPendentes e servicospendentes são nomes diferentes. Quando o programa usa uma variável inexistente, compare a escrita com a declaração antes de mudar a lógica.", brief: "Este código tem um erro. Execute para observá-lo, corrija o nome usado na saída e execute de novo. O resultado deve ser 3.", hint: "Compare o P de servicosPendentes na declaração e na chamada Console.WriteLine. Use a mesma escrita nas duas linhas.", starter: "int servicosPendentes = 3;\nConsole.WriteLine(servicospendentes);", expected: "3", verification: "Console.WriteLine(servicosPendentes == 3);", required: [/\bint\s+servicosPendentes\s*=/, /Console\.WriteLine\s*\(\s*servicosPendentes\s*\)/], solution: "int servicosPendentes = 3;\nConsole.WriteLine(servicosPendentes);" },
  { id: "quiz-update", kind: "quiz", title: "Acompanhe a mudança", topic: "Estado de uma variável", goal: "Ler um programa em ordem e acompanhar o valor atual.", prompt: "Depois destas instruções, qual número aparece?", code: "int pendentes = 4;\npendentes = pendentes + 3;\npendentes = pendentes - 2;\nConsole.WriteLine(pendentes);", options: ["4", "5", "7"], answer: 1, feedback: ["4 é o valor inicial. Ele muda nas duas instruções seguintes: primeiro 7, depois 5.", "Isso: 4 + 3 = 7; depois 7 - 2 = 5. O console mostra o valor atual.", "7 é o valor intermediário. Ainda há a subtração de 2 antes da saída."] },
  { id: "delivery", kind: "code", title: "Entregue seu primeiro resumo", topic: "Variáveis em conjunto", goal: "Combinar texto, números e cálculo em um pequeno programa independente.", lesson: "Agora reúna o que praticou. Escolha string para o nome e int para as quantidades. Calcule a diferença usando as variáveis e mostre os resultados na ordem pedida.", brief: 'OrbiServiços atende a cliente "Nina". Há 12 serviços no total e 4 concluídos. Declare cliente, totalServicos, servicosConcluidos e calcule servicosPendentes. Exiba cliente na primeira linha e servicosPendentes na segunda.', hint: 'Use string cliente e três variáveis int. O cálculo é totalServicos - servicosConcluidos. São duas chamadas Console.WriteLine: uma para cliente, outra para servicosPendentes.', starter: "", expected: "Nina\n8", verification: 'Console.WriteLine(cliente == "Nina");\nConsole.WriteLine(totalServicos == 12);\nConsole.WriteLine(servicosConcluidos == 4);\nConsole.WriteLine(servicosPendentes == 8);', required: [/\bstring\s+cliente\s*=/, /\bint\s+totalServicos\s*=/, /\bint\s+servicosConcluidos\s*=/, /\bint\s+servicosPendentes\s*=\s*totalServicos\s*-\s*servicosConcluidos\s*;/, /Console\.WriteLine\s*\(\s*cliente\s*\)/, /Console\.WriteLine\s*\(\s*servicosPendentes\s*\)/], solution: 'string cliente = "Nina";\nint totalServicos = 12;\nint servicosConcluidos = 4;\nint servicosPendentes = totalServicos - servicosConcluidos;\nConsole.WriteLine(cliente);\nConsole.WriteLine(servicosPendentes);' },
];

// Ignore comments and string contents when checking syntax. Runtime checks still
// validate the actual values/output; these checks only target this lesson's skill.
export function codeStructure(code: string): string {
  return code.replace(/"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|\/\/[^\n]*|\/\*[\s\S]*?\*\//g, token => token.startsWith('"') || token.startsWith("'") ? '""' : "");
}
export function variableCodePassed(activity: VariableCode, code: string, output: string, verification?: string): boolean {
  const source = codeStructure(code);
  const checks = activity.verification.split("\n").length;
  return !/\bint\s+\w+\s*=\s*"/.test(source) && activity.required.every(pattern => pattern.test(source)) && output.trim() === activity.expected && verification?.trim() === Array(checks).fill("true").join("\n");
}
export type VariablesProgress = { version: 1; active: string; drafts: Record<string, string>; done: string[]; answers: Record<string, number> };
export const variablesKey = (userId: string | number) => `orbitamos-csharp-variables-v1-${userId}`;
export const newVariablesProgress = (): VariablesProgress => ({ version: 1, active: "guided", drafts: {}, done: [], answers: {} });
export function readVariablesProgress(raw: string | null, legacyRaw: string | null = null, activities: VariableActivity[] = variableActivities, migrate = true): VariablesProgress {
  const base = newVariablesProgress();
  try {
    const value = JSON.parse(raw || "null");
    if (value?.version === 1) {
      const ids = activities.map(a => a.id);
      base.active = ids.includes(value.active) ? value.active : "guided";
      for (const a of activities) {
        if (a.kind === "code" && typeof value.drafts?.[a.id] === "string") base.drafts[a.id] = value.drafts[a.id].slice(0, 100000);
        if (a.kind === "quiz" && Number.isInteger(value.answers?.[a.id]) && value.answers[a.id] >= 0 && value.answers[a.id] < a.options.length) base.answers[a.id] = value.answers[a.id];
        if (Array.isArray(value.done) && value.done.includes(a.id) && (a.kind !== "quiz" || base.answers[a.id] === a.answer)) base.done.push(a.id);
      }
      return base;
    }
  } catch { /* Recover with the older pilot when available. */ }
  if (!migrate) return base;
  const legacy = readCSharpProgress(legacyRaw);
  base.done = ["guided", "transfer", "debug"].filter(id => legacy[id as "guided" | "transfer" | "debug"]);
  base.drafts = { ...legacy.drafts };
  base.active = variableActivities.find(a => !base.done.includes(a.id))?.id ?? "guided";
  return base;
}
export { csharpPilot, csharpProgressKey };
