import type { Desafio } from "./desafios";
import { readVariablesProgress, type VariableActivity } from "./csharpVariables";

export const conditionsPilot: Desafio = {
  slug: "trilha-csharp-condicoes-v1", titulo: "Decida se há trabalho pendente", descricao: "Faça uma decisão usando uma quantidade.", linguagem: "csharp", dificuldade: "iniciante", categoria: "Condicionais", minutos: 10, codigoInicial: "", exemplo: "Há trabalho",
  testCode: "Console.WriteLine(pendentes == 3);",
  steps: [{ instrucao: 'Declare int pendentes = 3. Se pendentes for maior que zero, exiba "Há trabalho".', codigoExemplo: 'int pendentes = 3;\nif (pendentes > 0) {\n    Console.WriteLine("Há trabalho");\n}', dica: "if significa se. > compara dois valores. As chaves delimitam o que será executado quando a condição for verdadeira.", acerto: "Você escreveu sua primeira decisão. Agora vamos entender o outro caminho e testar diferentes entradas.", erro: "Confira pendentes, a comparação > 0 e a mensagem Há trabalho.", validacao: (_, output, verification) => output.trim() === "Há trabalho" && verification?.trim() === "true" }],
};
export const conditionsActivities: VariableActivity[] = [
  { id: "guided", kind: "guided", title: "Escreva sua primeira decisão", topic: "if e comparação", goal: "Executar uma instrução somente quando uma condição for verdadeira." },
  { id: "quiz-branch", kind: "quiz", title: "Qual caminho será executado?", topic: "if / else", goal: "Identificar o caminho escolhido por uma condição.", code: 'int pendentes = 0;\nif (pendentes > 0) {\n    Console.WriteLine("Trabalhar");\n} else {\n    Console.WriteLine("Tudo entregue");\n}', prompt: "O que aparece no console?", options: ["Trabalhar", "Tudo entregue", "As duas mensagens"], answer: 1, feedback: ["0 não é maior que 0. A condição é falsa; o bloco if é pulado.", "Certo. Como 0 > 0 é falso, apenas o bloco else executa.", "if e else são caminhos alternativos: neste caso, apenas o else executa."] },
  { id: "branches", kind: "code", title: "Mostre os dois caminhos", topic: "if e else na prática", goal: "Tratar tanto a existência quanto a ausência de serviços pendentes.", lesson: "Use if (condição) { ... } para o caso verdadeiro e else { ... } para o contrário. Não coloque ponto e vírgula depois de if (...).", brief: 'Declare int pendentes = 2. Se pendentes > 0, exiba "Trabalhar". Caso contrário, exiba "Tudo entregue". Seu programa também será testado com pendentes igual a zero.', hint: 'Escreva uma comparação dentro dos parênteses de if. Feche o primeiro bloco antes de abrir else. Cada mensagem usa Console.WriteLine e fica dentro do seu bloco.', starter: "", expected: "Trabalhar", verification: "Console.WriteLine(pendentes == 2);", required: [/\bint\s+pendentes\s*=/, /\bif\s*\(\s*pendentes\s*>\s*0\s*\)/, /\belse\s*{/], solution: 'int pendentes = 2;\nif (pendentes > 0) {\n    Console.WriteLine("Trabalhar");\n} else {\n    Console.WriteLine("Tudo entregue");\n}', cases: [{ label: "Nenhum serviço pendente", values: { pendentes: "0" }, expected: "Tudo entregue" }, { label: "Cinco serviços pendentes", values: { pendentes: "5" }, expected: "Trabalhar" }] },
  { id: "threshold", kind: "code", title: "Inclua o valor do limite", topic: ">= e limites", goal: "Distinguir maior que de maior ou igual em uma regra de negócio.", lesson: "> exclui o valor exato do limite. >= inclui: 100 >= 100 é verdadeiro. Testar o limite ajuda a descobrir erros que um valor distante não mostra.", brief: 'Declare int valorPedido = 100. Pedidos de 100 ou mais têm "Frete grátis"; abaixo disso, mostre "Frete pago". Use if/else. Vamos testar 99, 100 e 101.', hint: "Use valorPedido >= 100. O sinal de igual inclui o pedido de exatamente 100 na promoção.", starter: "", expected: "Frete grátis", verification: "Console.WriteLine(valorPedido == 100);", required: [/\bint\s+valorPedido\s*=/, /\bif\s*\(/, /\belse\s*{/], solution: 'int valorPedido = 100;\nif (valorPedido >= 100) {\n    Console.WriteLine("Frete grátis");\n} else {\n    Console.WriteLine("Frete pago");\n}', cases: [{ label: "Pedido de 99", values: { valorPedido: "99" }, expected: "Frete pago" }, { label: "Pedido de 101", values: { valorPedido: "101" }, expected: "Frete grátis" }] },
  { id: "quiz-equality", kind: "quiz", title: "Guardar ou comparar?", topic: "= versus ==", goal: "Separar atribuição de comparação.", prompt: "Você quer verificar se pendentes é igual a zero. Qual condição usar?", options: ["pendentes = 0", "pendentes == 0", "pendentes > 0"], answer: 1, feedback: ["Um = atribui um valor. Para comparar igualdade, use dois: ==.", "Isso. == compara os valores; = guarda um novo valor na variável.", "> verifica se é maior, não se é igual a zero."] },
  { id: "both", kind: "code", title: "Exija as duas condições", topic: "bool e &&", goal: "Combinar duas condições que precisam ser verdadeiras ao mesmo tempo.", lesson: "bool guarda true ou false, sem aspas. && significa E: as duas condições precisam ser verdadeiras. Exemplo: pago && disponivel. Use !pago para negar um valor booleano.", brief: 'Declare bool pago = true e bool disponivel = true. Mostre "Liberado" apenas quando os dois forem verdadeiros; caso contrário, "Aguardar". Use if/else e &&.', hint: "A condição pode ser if (pago && disponivel). Não escreva true e false entre aspas.", starter: "", expected: "Liberado", verification: "Console.WriteLine(pago == true);\nConsole.WriteLine(disponivel == true);", required: [/\bbool\s+pago\s*=/, /\bbool\s+disponivel\s*=/, /\bif\s*\([^)]*&&[^)]*\)/, /\belse\s*{/], solution: 'bool pago = true;\nbool disponivel = true;\nif (pago && disponivel) {\n    Console.WriteLine("Liberado");\n} else {\n    Console.WriteLine("Aguardar");\n}', cases: [{ label: "Sem pagamento", values: { pago: "false" }, expected: "Aguardar" }, { label: "Sem disponibilidade", values: { disponivel: "false" }, expected: "Aguardar" }, { label: "Nenhuma condição atendida", values: { pago: "false", disponivel: "false" }, expected: "Aguardar" }] },
  { id: "either", kind: "code", title: "Aceite uma das alternativas", topic: "|| e negação", goal: "Representar uma regra na qual uma das alternativas basta.", lesson: "|| significa OU: basta uma condição verdadeira. Com ! você inverte um bool: !bloqueado é verdadeiro quando bloqueado é falso. Nesta prática, use OU.", brief: 'Declare bool urgente = false e bool clienteVip = true. Se urgente OU clienteVip forem verdadeiros, mostre "Prioridade". Senão, mostre "Fila normal".', hint: "A comparação é urgente || clienteVip. A regra aceita qualquer um dos dois, não exige ambos.", starter: "", expected: "Prioridade", verification: "Console.WriteLine(urgente == false);\nConsole.WriteLine(clienteVip == true);", required: [/\bbool\s+urgente\s*=/, /\bbool\s+clienteVip\s*=/, /\bif\s*\([^)]*\|\|[^)]*\)/, /\belse\s*{/], solution: 'bool urgente = false;\nbool clienteVip = true;\nif (urgente || clienteVip) {\n    Console.WriteLine("Prioridade");\n} else {\n    Console.WriteLine("Fila normal");\n}', cases: [{ label: "Urgente, cliente comum", values: { urgente: "true", clienteVip: "false" }, expected: "Prioridade" }, { label: "Sem prioridade", values: { urgente: "false", clienteVip: "false" }, expected: "Fila normal" }] },
  { id: "debug-limit", kind: "code", title: "Corrija o limite da promoção", topic: "Depuração de condição", goal: "Corrigir uma regra que exclui um caso válido.", lesson: "Nem todo bug causa erro de execução. O programa pode rodar e tomar a decisão errada. Compare a regra escrita com os casos de teste, principalmente o limite.", brief: 'A promoção vale para pedidos de 100 ou mais. O código abaixo rejeita exatamente 100. Execute, observe a saída e corrija a comparação.', hint: "O problema não está no valorPedido. Falta incluir a igualdade na comparação do if.", starter: 'int valorPedido = 100;\nif (valorPedido > 100) {\n    Console.WriteLine("Promoção");\n} else {\n    Console.WriteLine("Sem promoção");\n}', expected: "Promoção", verification: "Console.WriteLine(valorPedido == 100);", required: [/\bint\s+valorPedido\s*=/, /\bif\s*\(/, /\belse\s*{/], solution: 'int valorPedido = 100;\nif (valorPedido >= 100) {\n    Console.WriteLine("Promoção");\n} else {\n    Console.WriteLine("Sem promoção");\n}', cases: [{ label: "Abaixo do limite", values: { valorPedido: "99" }, expected: "Sem promoção" }, { label: "Acima do limite", values: { valorPedido: "101" }, expected: "Promoção" }] },
  { id: "quiz-and", kind: "quiz", title: "Leia a regra completa", topic: "Combinação de condições", goal: "Acompanhar uma decisão que combina quantidade e estado.", code: "int pendentes = 2;\nbool pago = false;\n// condição: pendentes > 0 && pago", prompt: "A condição acima é verdadeira?", options: ["Sim, porque há pendências", "Não, porque o pagamento é falso", "Sim, porque && aceita uma das condições"], answer: 1, feedback: ["Há pendências, mas && também exige que pago seja true.", "Certo. Com &&, as duas partes precisam ser verdadeiras. pago é false.", "Quem aceita uma das condições é ||. && exige as duas."] },
  { id: "delivery", kind: "code", title: "Entregue a decisão do OrbiServiços", topic: "Variáveis + condições", goal: "Combinar dados, cálculo e decisão em um programa independente.", lesson: "Reúna o que já praticou. Calcule o saldo usando variáveis. Depois use if/else if/else para separar três situações. Os ramos são avaliados em ordem; apenas o primeiro verdadeiro executa.", brief: 'Declare string cliente = "Nina", int totalServicos = 12, int concluidos = 4 e bool pago = true. Calcule int pendentes = totalServicos - concluidos. Mostre cliente. Se pendentes == 0, mostre "Tudo entregue". Senão, se pago for verdadeiro, mostre "Pode trabalhar". Caso contrário, "Aguardar pagamento".', hint: "Escreva primeiro as cinco variáveis e mostre cliente. Depois use if (pendentes == 0), else if (pago) e else, cada um com sua mensagem dentro das chaves.", starter: "", expected: "Nina\nPode trabalhar", verification: 'Console.WriteLine(cliente == "Nina");\nConsole.WriteLine(totalServicos == 12);\nConsole.WriteLine(concluidos == 4);\nConsole.WriteLine(pago == true);\nConsole.WriteLine(pendentes == 8);', required: [/\bstring\s+cliente\s*=/, /\bint\s+totalServicos\s*=/, /\bint\s+concluidos\s*=/, /\bbool\s+pago\s*=/, /\bint\s+pendentes\s*=\s*totalServicos\s*-\s*concluidos\s*;/, /\bif\s*\(/, /\belse\s+if\s*\(/, /Console\.WriteLine\s*\(\s*cliente\s*\)/], solution: 'string cliente = "Nina";\nint totalServicos = 12;\nint concluidos = 4;\nbool pago = true;\nint pendentes = totalServicos - concluidos;\nConsole.WriteLine(cliente);\nif (pendentes == 0) {\n    Console.WriteLine("Tudo entregue");\n} else if (pago) {\n    Console.WriteLine("Pode trabalhar");\n} else {\n    Console.WriteLine("Aguardar pagamento");\n}', cases: [{ label: "Tudo concluído", values: { concluidos: "12" }, expected: "Nina\nTudo entregue" }, { label: "Pendências sem pagamento", values: { pago: "false" }, expected: "Nina\nAguardar pagamento" }, { label: "Concluído mesmo sem pagamento", values: { concluidos: "12", pago: "false" }, expected: "Nina\nTudo entregue" }] },
];
export const conditionsKey = (id: string | number) => `orbitamos-csharp-conditions-v1-${id}`;
export const readConditionsProgress = (raw: string | null) => readVariablesProgress(raw, null, conditionsActivities, false);
