export type Buddy = "parenteses" | "colchetes" | "chaves" | "espacos";
export const buddyTerms: Record<Buddy, string> = { parenteses: "Parênteses", colchetes: "Colchetes", chaves: "Chaves", espacos: "Indentação" };
export const buddies: Record<Buddy, { name: string; symbol: string; color: string; role: string; speech: string; examples: string[] }> = {
  parenteses: { name: "Pipo & Pop", symbol: "( )", color: "#ffd580", role: "Os mensageiros", speech: "Nós trabalhamos em dupla! Aqui, levamos os argumentos para uma chamada. Também agrupamos expressões. Não moramos em uma linguagem só.", examples: ['Python: print("Oi!")', 'JavaScript: console.log("Oi!")', 'C#: Console.WriteLine("Oi!");'] },
  colchetes: { name: "Lili", symbol: "[ ]", color: "#a9d9ff", role: "A exploradora", speech: "Ajudo a acessar um item pelo índice nas três linguagens desta aventura. Python e JavaScript também me usam para escrever listas e arrays. O primeiro índice é 0!", examples: ['Python: frutas = ["uva", "pera"]', 'JavaScript: frutas[0]', 'C#: nomes[0]'] },
  chaves: { name: "Cora", symbol: "{ }", color: "#f7b5cc", role: "A construtora", speech: "Em JavaScript e C#, delimito blocos. Em Python, não faço esse trabalho, mas apareço em dicionários e conjuntos. Minha função depende do contexto!", examples: ['JavaScript: if (chuva) { abrigar(); }', 'C#: if (chuva) { Abrigar(); }', 'Python: estoque = {"mel": 2}'] },
  espacos: { name: "Nino", symbol: "····", color: "#b6edb5", role: "O guia dos passos", speech: "Indentação é o recuo no começo da linha. Em Python, ela define os blocos. Aqui usamos 4 espaços por nível: é a convenção, não um número mágico. Não misture tabs e espaços.", examples: ['Python: if chuva:\n    abrigar()', 'Mesmo recuo = mesmo nível de bloco.', 'JavaScript e C#: recuar ajuda a ler; as chaves delimitam o bloco.'] },
};
type Base = { id: string; chapter: string; title: string; language: "Python" | "JavaScript" | "C#"; buddy: Buddy; story: string; goal: string; hint: string; lesson: string; output: string[]; place: "correio" | "mochila" | "abrigo" | "festival" };
type Socket = Base & { kind: "socket"; before: string; middle: string; after: string; answer: Exclude<Buddy, "espacos"> };
type Indent = Base & { kind: "indent"; lines: string[]; initial: number[]; answer: number[]; movable: number[] };
export type VillageLevel = Socket | Indent;
export const villageLevels: VillageLevel[] = [
  { id: "correio", chapter: "1 · Conheça a turma", title: "O correio ficou mudo", language: "Python", buddy: "parenteses", place: "correio", kind: "socket", before: "print", middle: '"Oi, Vila!"', after: "", answer: "parenteses", story: "A ventania levou o encaixe do megafone! Sou Pipo, e meu irmão Pop segura a outra ponta. Vamos entregar uma mensagem?", goal: "Escolha uma dupla e toque no encaixe para completar a chamada de print.", hint: "Uma chamada usa nome da função, abertura de parênteses, argumentos e fechamento.", lesson: "print(...) é uma chamada. O texto entre aspas é o argumento que será mostrado. Python também usa parênteses!", output: ["Oi, Vila!" ] },
  { id: "mochila", chapter: "1 · Conheça a turma", title: "As estrelas de Lili", language: "Python", buddy: "colchetes", place: "mochila", kind: "socket", before: "estrelas = ", middle: '"azul", "dourada"', after: "\nprint(estrelas)", answer: "colchetes", story: "Sou Lili! Achei duas estrelas caídas. Quero guardá-las numa lista para levar ao festival.", goal: "Complete a lista com a dupla certa.", hint: "Neste exemplo Python, uma lista é escrita entre [ e ]. Chaves criariam outro tipo de coleção.", lesson: "Os colchetes criam esta lista Python. Parênteses aqui formariam uma tupla e chaves formariam um conjunto, não a lista pedida.", output: ["['azul', 'dourada']"] },
  { id: "primeiro-item", chapter: "1 · Conheça a turma", title: "Um presente, não a mochila toda", language: "JavaScript", buddy: "colchetes", place: "mochila", kind: "socket", before: 'const presentes = ["lua", "sol"];\nconsole.log(presentes', middle: "0", after: ");", answer: "colchetes", story: "A lua é o primeiro presente. Minha mochila viaja para JavaScript também. Vamos buscar só esse item?", goal: "Encaixe a dupla que acessa o item de índice 0.", hint: "presentes[0] acessa o primeiro item. presentes(0) tentaria chamar presentes como função.", lesson: "Aqui [0] acessa um item; não cria outra lista. O mesmo símbolo tem funções diferentes conforme o lugar.", output: ["lua"] },
  { id: "abrigo", chapter: "1 · Conheça a turma", title: "O abrigo de Cora", language: "JavaScript", buddy: "chaves", place: "abrigo", kind: "socket", before: "const chuva = true;\nif (chuva) ", middle: '\n    console.log("Abrigo aberto");\n', after: "", answer: "chaves", story: "Sou Cora, a construtora. Em JavaScript, minhas duas portas marcam o começo e o fim deste bloco do if.", goal: "Construa o bloco com chaves, envolvendo a ação do abrigo.", hint: "Neste bloco usamos { para abrir e } para fechar. Recuar ajuda a ler, mas não substitui essas chaves.", lesson: "Neste JavaScript, { } delimitam o bloco do if. Os espaços ajudam a enxergar a estrutura; não são eles que delimitam o bloco.", output: ["Abrigo aberto"] },
  { id: "csharp", chapter: "1 · Conheça a turma", title: "Uma ligação para C#", language: "C#", buddy: "parenteses", place: "correio", kind: "socket", before: "Console.WriteLine", middle: '"Festival chegando!"', after: ";", answer: "parenteses", story: "Pipo e Pop de novo! O nome do mensageiro mudou, mas nossa dupla também trabalha nas chamadas em C#.", goal: "Complete a chamada de Console.WriteLine.", hint: "Use parênteses em volta do argumento. O ponto e vírgula já está no final da instrução.", lesson: "Console.WriteLine(...) chama um método em C#. Os parênteses envolvem os argumentos; o ponto e vírgula encerra esta instrução.", output: ["Festival chegando!"] },
  { id: "cora-python", chapter: "2 · O segredo de Python", title: "Cora também visita Python", language: "Python", buddy: "chaves", place: "mochila", kind: "socket", before: "estoque = ", middle: '"mel": 2', after: '\nprint(estoque["mel"])', answer: "chaves", story: "Surpresa: eu também apareço em Python! Hoje não construo um bloco. Guardo pares de chave e valor num dicionário.", goal: "Guarde a chave mel e o valor 2 dentro de um dicionário.", hint: "O dicionário deste exemplo usa {\"mel\": 2}. Os colchetes na linha seguinte consultam a chave mel.", lesson: "Python usa { } para este dicionário. A chave é o texto mel e o valor é 2. Isso não é um bloco de instruções.", output: ["2"] },
  { id: "quatro-passos", chapter: "2 · O segredo de Python", title: "Nino encontra seu lugar", language: "Python", buddy: "espacos", place: "abrigo", kind: "indent", lines: ["chuva = True", "if chuva:", 'print("Abrigo aberto")'], initial: [0, 0, 0], answer: [0, 0, 1], movable: [2], story: "Sou Nino. No bairro Python, o recuo mostra quem está dentro do bloco. Me leve quatro passos para a direita, até o abrigo!", goal: "Coloque a ação dentro do if usando +4 espaços. Os pontinhos mostram espaços, não são código digitado.", hint: "Depois do if com dois-pontos, a ação deve ficar um nível para dentro. Aqui cada nível tem 4 espaços.", lesson: "Agora print pertence ao if. Python exige um corpo indentado após esse cabeçalho. Usamos 4 espaços como convenção e mantemos o recuo consistente.", output: ["Abrigo aberto"] },
  { id: "lanternas", chapter: "2 · O segredo de Python", title: "Três luzes, um anúncio", language: "Python", buddy: "espacos", place: "festival", kind: "indent", lines: ["for luz in range(3):", 'print("Luz acesa")', 'print("Pronto!")'], initial: [0, 0, 1], answer: [0, 1, 0], movable: [1, 2], story: "Precisamos acender três lanternas, mas anunciar Pronto! uma vez só. Dentro do laço a ação repete; fora dele, segue depois.", goal: "Leve Luz acesa para dentro do for e Pronto! de volta para fora.", hint: "Linha 2: 4 espaços. Linha 3: nenhum recuo. Se Pronto! ficar dentro, o anúncio também repetirá três vezes.", lesson: "O recuo mudou quantas vezes cada ação acontece. O print fora do laço só acontece depois das três voltas.", output: ["Luz acesa", "Luz acesa", "Luz acesa", "Pronto!"] },
  { id: "duas-portas", chapter: "3 · Cuide do festival", title: "Um bloco dentro do outro", language: "Python", buddy: "espacos", place: "festival", kind: "indent", lines: ["festa = True", "if festa:", "for luz in range(2):", 'print("Estrela acesa")'], initial: [0, 0, 0, 0], answer: [0, 0, 1, 2], movable: [2, 3], story: "A festa abriu! Dentro dela há um laço. E dentro do laço há uma estrela. Dois níveis, duas pequenas viagens para a direita.", goal: "Coloque o for dentro do if e o print dentro do for.", hint: "O for usa 4 espaços; o print, 8. Oito espaços aqui representam dois níveis, não uma regra para todo print.", lesson: "Blocos podem morar dentro de outros. O print está dois níveis para dentro: só entra se festa for verdadeira e repete duas vezes.", output: ["Estrela acesa", "Estrela acesa"] },
  { id: "festa-sem-chuva", chapter: "3 · Cuide do festival", title: "A festa não depende da chuva", language: "Python", buddy: "espacos", place: "festival", kind: "indent", lines: ["chuva = False", "if chuva:", 'print("Pegue o guarda-chuva")', 'print("Vamos festejar!")'], initial: [0, 0, 1, 1], answer: [0, 0, 1, 0], movable: [3], story: "Não está chovendo! O código atual é válido, mas o convite ficou preso dentro do if. A festa precisa acontecer mesmo sem chuva.", goal: "Tire apenas o convite do bloco. O aviso de guarda-chuva deve continuar dentro.", hint: "Use −4 espaços na última linha. Com chuva = False, nenhuma ação dentro do if será realizada.", lesson: "Um código pode ser válido e ainda fazer outra coisa. Tirar o último print do if faz o convite aparecer mesmo quando a condição é falsa.", output: ["Vamos festejar!"] },
];
export type VillageAttempt = { pair: Buddy | null; indents: number[] };
export function initialAttempt(level: VillageLevel): VillageAttempt { return { pair: null, indents: level.kind === "indent" ? [...level.initial] : [] }; }
export function villageCode(level: VillageLevel, attempt: VillageAttempt) {
  if (level.kind === "indent") return level.lines.map((line, i) => " ".repeat(Math.max(0, Math.min(2, attempt.indents[i] ?? 0)) * 4) + line).join("\n");
  const pair = attempt.pair === "parenteses" ? ["(", ")"] : attempt.pair === "colchetes" ? ["[", "]"] : attempt.pair === "chaves" ? ["{", "}"] : ["?", "?"];
  return level.before + pair[0] + level.middle + pair[1] + level.after;
}
// Deterministic simulation of authored puzzles, NOT an arbitrary Python/JS/.NET runtime.
export function evaluateVillage(level: VillageLevel, attempt: VillageAttempt): { ok: boolean; message: string; output: string[] } {
  const ok = level.kind === "socket" ? attempt.pair === level.answer : level.answer.every((value, i) => attempt.indents[i] === value);
  if (ok) return { ok, message: level.lesson, output: level.output };
  if (level.kind === "socket") return { ok, message: attempt.pair ? `${buddies[attempt.pair].name} tem outro trabalho neste exemplo. ${level.hint}` : "Escolha um personagem e toque no encaixe brilhante antes de testar.", output: [] };
  if (level.id === "festa-sem-chuva" && attempt.indents[3] === 1) return { ok, message: "Nenhuma mensagem apareceu. Não é erro de sintaxe: chuva é False, então o convite dentro do if não acontece. Como fazê-lo acontecer fora desse bloco?", output: [] };
  if (level.id === "festa-sem-chuva" && attempt.indents[3] === 2) return { ok, message: "Esse recuo extra não abre um bloco novo sozinho. Não há um cabeçalho com dois-pontos antes desta linha para justificar outro nível. Traga o convite de volta para fora do if.", output: [] };
  if (level.id === "lanternas" && attempt.indents[1] === 1 && attempt.indents[2] === 1) return { ok, message: "O anúncio repetiu três vezes! Este código é válido, mas Pronto! também está dentro do laço. Leve o anúncio para fora.", output: ["Luz acesa", "Pronto!", "Luz acesa", "Pronto!", "Luz acesa", "Pronto!"] };
  return { ok, message: `O caminho ainda não chega ao bloco certo. ${level.hint}`, output: [] };
}
export type VillageSave = { version: 1; completed: string[]; current: number };
export function readVillageSave(raw: string | null): VillageSave {
  const empty: VillageSave = { version: 1, completed: [], current: 0 };
  try {
    const data = JSON.parse(raw ?? "null");
    if (data?.version !== 1 || !Array.isArray(data.completed)) return empty;
    return { version: 1, completed: [...new Set<string>(data.completed.filter((id: unknown) => typeof id === "string" && villageLevels.some(level => level.id === id)))], current: Number.isInteger(data.current) && data.current >= 0 && data.current < villageLevels.length ? data.current : 0 };
  } catch { return empty; }
}
export const villageStorageKey = (userId: string) => `orbitamos-vila-v1-${userId}`;
