import { requireSupabase } from "@/lib/supabase";

export type AdminJob = {
  id?: number; title:string; description:string; type:string; workModel:string; status:"draft"|"open"|"paused"|"closed";
  skills:string[]; requirements:string[]; budgetLabel:string; scope:string; openings:number; applicationDeadline:string;
};
export type AdminApplication = { id:number; jobId:number; userId:string; candidateName:string; candidateEmail:string; jobTitle:string; status:"pending"|"reviewing"|"accepted"|"declined"|"withdrawn"; coverLetter:string; feedback:string; createdAt:string };
export type AdminProject = { id?:number; title:string; description:string; status:"todo"|"in_progress"|"completed"|"paused"; clientName:string; priority:"low"|"medium"|"high"|"urgent"; startDate:string; dueDate:string; progress:number; briefing:string; links:Array<{label:string;url:string}> };
export type WorkspaceMember = { id:string; name:string; email:string; avatarUrl?:string|null; roleLabel?:string };
export type NotificationItem = { id:number; type:string; title:string; body:string; href?:string|null; readAt?:string|null; createdAt:string };
export type PortfolioItem = { id?:number; title:string; description:string; projectUrl:string; imageUrl:string; skills:string[]; featured:boolean; sortOrder:number };

export async function listAdminJobs():Promise<AdminJob[]> { const {data,error}=await requireSupabase().from("v3_jobs").select("*").order("created_at",{ascending:false}); if(error)throw new Error("Não foi possível carregar as vagas."); return (data??[]).map(r=>({id:r.id,title:r.title,description:r.description,type:r.type,workModel:r.work_model,status:r.status,skills:r.skills??[],requirements:r.requirements??[],budgetLabel:r.budget_label??"",scope:r.scope??"",openings:r.openings??1,applicationDeadline:r.application_deadline??""})); }
export async function saveAdminJob(job:AdminJob):Promise<void> { const client=requireSupabase(); const {data:{user}}=await client.auth.getUser(); const payload={title:job.title.trim(),description:job.description.trim(),type:job.type,work_model:job.workModel,status:job.status,skills:job.skills,requirements:job.requirements,budget_label:job.budgetLabel.trim()||null,scope:job.scope.trim()||null,openings:job.openings,application_deadline:job.applicationDeadline||null,published_at:job.status==="open"?new Date().toISOString():null,created_by:user?.id}; const query=job.id?client.from("v3_jobs").update(payload).eq("id",job.id):client.from("v3_jobs").insert(payload); const {error}=await query;if(error)throw new Error(error.message||"Não foi possível salvar a vaga."); }

export async function listAdminApplications():Promise<AdminApplication[]> { const client=requireSupabase(); const {data,error}=await client.from("v3_job_applications").select("*").order("created_at",{ascending:false}); if(error)throw new Error("Não foi possível carregar candidaturas."); const rows=data??[]; const userIds=[...new Set(rows.map(r=>r.user_id))]; const jobIds=[...new Set(rows.map(r=>r.job_id))]; const [{data:profiles},{data:jobs}]=await Promise.all([userIds.length?client.from("v3_profiles").select("id,name,email").in("id",userIds):Promise.resolve({data:[]}),jobIds.length?client.from("v3_jobs").select("id,title").in("id",jobIds):Promise.resolve({data:[]})]); return rows.map(r=>{const p=(profiles??[]).find(x=>x.id===r.user_id);const j=(jobs??[]).find(x=>x.id===r.job_id);return{id:r.id,jobId:r.job_id,userId:r.user_id,candidateName:p?.name??"Candidato",candidateEmail:p?.email??"",jobTitle:j?.title??"Vaga",status:r.status,coverLetter:r.cover_letter??"",feedback:r.feedback??"",createdAt:r.created_at};}); }
export async function updateAdminApplication(id:number,status:AdminApplication["status"],feedback:string):Promise<void>{const {error}=await requireSupabase().from("v3_job_applications").update({status,feedback:feedback.trim()||null,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw new Error("Não foi possível atualizar a candidatura.");}

export async function listAdminProjects():Promise<AdminProject[]>{const {data,error}=await requireSupabase().from("v3_collaborator_projects").select("*").order("updated_at",{ascending:false});if(error)throw new Error("Não foi possível carregar projetos.");return(data??[]).map(r=>({id:r.id,title:r.title,description:r.description,status:r.status,clientName:r.client_name??"",priority:r.priority??"medium",startDate:r.start_date??"",dueDate:r.due_date??"",progress:r.progress??0,briefing:r.briefing??"",links:Array.isArray(r.links)?r.links:[]}));}
export async function saveAdminProject(project:AdminProject):Promise<void>{const payload={title:project.title.trim(),description:project.description.trim(),status:project.status,client_name:project.clientName.trim()||null,priority:project.priority,start_date:project.startDate||null,due_date:project.dueDate||null,progress:project.progress,briefing:project.briefing.trim()||null,links:project.links,updated_at:new Date().toISOString()};const client=requireSupabase();const query=project.id?client.from("v3_collaborator_projects").update(payload).eq("id",project.id):client.from("v3_collaborator_projects").insert(payload);const{error}=await query;if(error)throw new Error("Não foi possível salvar o projeto.");}
export async function listProjectMembers(projectId:number):Promise<WorkspaceMember[]>{const client=requireSupabase();const{data,error}=await client.from("v3_project_members").select("user_id,role_label").eq("project_id",projectId);if(error)throw new Error("Não foi possível carregar o squad.");const ids=(data??[]).map(r=>r.user_id);if(!ids.length)return[];const{data:profiles}=await client.from("v3_profiles").select("id,name,email,avatar_url").in("id",ids);return(profiles??[]).map(p=>({id:p.id,name:p.name??"Colaborador",email:p.email,avatarUrl:p.avatar_url,roleLabel:(data??[]).find(m=>m.user_id===p.id)?.role_label??"Colaborador"}));}
export async function listAvailableCollaborators():Promise<WorkspaceMember[]>{const{data,error}=await requireSupabase().from("v3_profiles").select("id,name,email,avatar_url").or("role.eq.FREELANCER,is_internal.eq.true").order("name");if(error)throw new Error("Não foi possível carregar colaboradores.");return(data??[]).map(p=>({id:p.id,name:p.name??"Colaborador",email:p.email,avatarUrl:p.avatar_url}));}
export async function addProjectMember(projectId:number,userId:string,roleLabel:string):Promise<void>{const{error}=await requireSupabase().from("v3_project_members").upsert({project_id:projectId,user_id:userId,role_label:roleLabel.trim()||"Colaborador"});if(error)throw new Error("Não foi possível adicionar o colaborador.");}
export async function removeProjectMember(projectId:number,userId:string):Promise<void>{const{error}=await requireSupabase().from("v3_project_members").delete().eq("project_id",projectId).eq("user_id",userId);if(error)throw new Error("Não foi possível remover o colaborador.");}

export async function listNotifications():Promise<NotificationItem[]>{const{data,error}=await requireSupabase().from("v3_notifications").select("*").order("created_at",{ascending:false}).limit(50);if(error)throw new Error("Não foi possível carregar notificações.");return(data??[]).map(r=>({id:r.id,type:r.type,title:r.title,body:r.body,href:r.href,readAt:r.read_at,createdAt:r.created_at}));}
export async function markNotificationRead(id:number):Promise<void>{const{error}=await requireSupabase().from("v3_notifications").update({read_at:new Date().toISOString()}).eq("id",id);if(error)throw new Error("Não foi possível marcar a notificação.");}
export async function markAllNotificationsRead():Promise<void>{const{error}=await requireSupabase().from("v3_notifications").update({read_at:new Date().toISOString()}).is("read_at",null);if(error)throw new Error("Não foi possível atualizar notificações.");}

export async function listPortfolioItems():Promise<PortfolioItem[]>{const{data,error}=await requireSupabase().from("v3_portfolio_items").select("*").order("sort_order");if(error)throw new Error("Não foi possível carregar o portfólio.");return(data??[]).map(r=>({id:r.id,title:r.title,description:r.description,projectUrl:r.project_url??"",imageUrl:r.image_url??"",skills:r.skills??[],featured:r.featured,sortOrder:r.sort_order}));}
export async function savePortfolioItem(item:PortfolioItem):Promise<void>{const client=requireSupabase();const{data:{user}}=await client.auth.getUser();if(!user)throw new Error("Sessão expirada.");const payload={user_id:user.id,title:item.title.trim(),description:item.description.trim(),project_url:item.projectUrl.trim()||null,image_url:item.imageUrl.trim()||null,skills:item.skills,featured:item.featured,sort_order:item.sortOrder,updated_at:new Date().toISOString()};const query=item.id?client.from("v3_portfolio_items").update(payload).eq("id",item.id):client.from("v3_portfolio_items").insert(payload);const{error}=await query;if(error)throw new Error("Não foi possível salvar o case.");}
export async function deletePortfolioItem(id:number):Promise<void>{const{error}=await requireSupabase().from("v3_portfolio_items").delete().eq("id",id);if(error)throw new Error("Não foi possível remover o case.");}

export async function requestAccountAction(type:"deletion"|"data_export",reason:string):Promise<void>{const client=requireSupabase();const{data:{user}}=await client.auth.getUser();if(!user)throw new Error("Sessão expirada.");const{error}=await client.from("v3_account_requests").insert({user_id:user.id,type,reason:reason.trim()||null});if(error?.code==="23505")throw new Error("Já existe uma solicitação em andamento.");if(error)throw new Error("Não foi possível registrar a solicitação.");}
export type AccountRequest={id:number;userId:string;userName:string;userEmail:string;type:"deletion"|"data_export";status:"pending"|"processing"|"completed"|"cancelled";reason:string;createdAt:string};
export async function listAccountRequests():Promise<AccountRequest[]>{const client=requireSupabase();const{data,error}=await client.from("v3_account_requests").select("*").order("created_at",{ascending:false});if(error)throw new Error("Não foi possível carregar solicitações.");const rows=data??[];const ids=[...new Set(rows.map(r=>r.user_id))];const{data:profiles}=ids.length?await client.from("v3_profiles").select("id,name,email").in("id",ids):{data:[]};return rows.map(r=>{const p=(profiles??[]).find(x=>x.id===r.user_id);return{id:r.id,userId:r.user_id,userName:p?.name??"Usuário",userEmail:p?.email??"",type:r.type,status:r.status,reason:r.reason??"",createdAt:r.created_at};});}
export async function updateAccountRequest(id:number,status:AccountRequest["status"]):Promise<void>{const{error}=await requireSupabase().from("v3_account_requests").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw new Error("Não foi possível atualizar a solicitação.");}
